/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_2do_parcial;

import Models.Farmacias;
import Models.lsarchivo;
//import cjb.ci.Validaciones;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Angeles
 */
public class Farmacia extends javax.swing.JFrame
{

    public static ML mul = new ML();
    public static NodoLista r = null;

    /**
     * Creates new form Farmacia
     */
    public Farmacia(ML m)
    {
        initComponents();
        mul = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FKey = new javax.swing.JTextField();
        FSociety = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FRFC = new javax.swing.JTextField();
        GFarmacia = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 18)); // NOI18N
        jLabel1.setText("Alta de Farmacias");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        FNombre.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 18)); // NOI18N
        FNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                FNombreActionPerformed(evt);
            }
        });
        FNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                FNombreKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 18)); // NOI18N
        jLabel3.setText("Ingresa la clave");

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 18)); // NOI18N
        jLabel4.setText("Ingresa la Sociedad");

        FKey.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 18)); // NOI18N
        FKey.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                FKeyActionPerformed(evt);
            }
        });
        FKey.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                FKeyKeyTyped(evt);
            }
        });

        FSociety.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 18)); // NOI18N
        FSociety.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                FSocietyActionPerformed(evt);
            }
        });
        FSociety.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                FSocietyKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 18)); // NOI18N
        jLabel2.setText("Ingresa el Nombre");

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 18)); // NOI18N
        jLabel5.setText("Ingresa el RFC");

        FRFC.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 18)); // NOI18N
        FRFC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                FRFCActionPerformed(evt);
            }
        });

        GFarmacia.setText("Guardar");
        GFarmacia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GFarmaciaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Casa.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FKey, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FSociety, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(GFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FNombre)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FKey)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FSociety, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(GFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_FNombreActionPerformed
    {//GEN-HEADEREND:event_FNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNombreActionPerformed

    private void FKeyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_FKeyActionPerformed
    {//GEN-HEADEREND:event_FKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FKeyActionPerformed

    private void FSocietyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_FSocietyActionPerformed
    {//GEN-HEADEREND:event_FSocietyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FSocietyActionPerformed

    private void FRFCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_FRFCActionPerformed
    {//GEN-HEADEREND:event_FRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FRFCActionPerformed

    private void GFarmaciaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GFarmaciaActionPerformed
    {//GEN-HEADEREND:event_GFarmaciaActionPerformed
        try
        {
            if (GuardarFarmacia() == 1)
            {
                FNombre.setText("");
                FKey.setText("");
                FRFC.setText("");
                FSociety.setText("");
                JOptionPane.showMessageDialog(this, "Se ha guardado la informacion");
            } else
            {
                JOptionPane.showMessageDialog(this, "Error Al Guardar");
            }
        } catch (IOException ex)
        {
            Logger.getLogger(Farmacia.class.getName()).log(Level.SEVERE, null, ex);
        }
        Ciudad c = new Ciudad(mul);
        NodoLista r = mul.r;
        c.mlgeneral = mul;
        c.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_GFarmaciaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void FNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_FNombreKeyTyped
    {//GEN-HEADEREND:event_FNombreKeyTyped
        //Validaciones.validaAlfanumerico(evt, 20, FNombre.getText());
    }//GEN-LAST:event_FNombreKeyTyped

    private void FKeyKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_FKeyKeyTyped
    {//GEN-HEADEREND:event_FKeyKeyTyped
        //Validaciones.validaAlfanumerico(evt, 20, FKey.getText());
    }//GEN-LAST:event_FKeyKeyTyped

    private void FSocietyKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_FSocietyKeyTyped
    {//GEN-HEADEREND:event_FSocietyKeyTyped
        //Validaciones.validaAlfanumerico(evt, 20, FSociety.getText());
    }//GEN-LAST:event_FSocietyKeyTyped

    public int GuardarFarmacia() throws IOException
    {
        if (FNombre.getText().length() > 0 && FKey.getText().length() > 0 && FRFC.getText().length() > 0 && FSociety.getText().length() > 0)
        {
            Models.Farmacias farmacia = new Farmacias();

            farmacia.setNombre(FNombre.getText());
            farmacia.setClave(FKey.getText());
            farmacia.setRFC(FRFC.getText());
            farmacia.setTDS(FSociety.getText());

            NodoLista nls = new NodoLista(FNombre.getText(), farmacia);
            String[] etqs = new String[1];
            etqs[0] = FNombre.getText();

            r = mul.inserta(etqs, 0, nls, r);
            mul.r = r;

            lsarchivo a = new lsarchivo();
            a.InsertarnuevaLista(mul);
            return 1;
        } else
        {
            JOptionPane.showMessageDialog(rootPane, "Error, favor de rellenar todos los campos");
            return 0;
        }
        //inserto nueva multilista en archivo
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Farmacia(mul).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FKey;
    private javax.swing.JTextField FNombre;
    private javax.swing.JTextField FRFC;
    private javax.swing.JTextField FSociety;
    private javax.swing.JButton GFarmacia;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
